wallpaper {
    monitor = DP-3
    path = /home/ro/dotfiles/wallpapers/marca.png
    fit_mode = cover
}

wallpaper {
    monitor = DP-2
    path = /home/ro/dotfiles/wallpapers/guts.png
    fit_mode = cover
}

splash = false
ipc = on
