preload = /home/devops/Dotfiles/wallpapers/guts.png
preload = /home/devops/Dotfiles/wallpapers/marca.png

wallpaper = DP-2,/home/devops/Dotfiles/wallpapers/guts.png
wallpaper = DP-1,/home/devops/Dotfiles/wallpapers/marca.png

splash = false
ipc = off
