monitor=DP-3,2560x1440@144,0x0,1
monitor=DP-2,1920x1080@144,2560x0,1

# Workspaces fijos por monitor
workspace=1, monitor:DP-3
workspace=3, monitor:DP-3
workspace=5, monitor:DP-3
workspace=7, monitor:DP-3
workspace=9, monitor:DP-3

workspace=2, monitor:DP-2
workspace=4, monitor:DP-2
workspace=6, monitor:DP-2
workspace=10, monitor:DP-2
